name: Generate OpenApiJson

# Runs this action whenever there are any changes to the master branch.
on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Checks out the entire repo.
    steps:
    - name: Checks out repo
      uses: actions/checkout@v3

    # Installs dependencies
    - name: Generate OpenAPI file
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        echo "INSTALLED DEPENDENCIES. GENERATING OPENAPI FILE"
        pwd
        python manage.py spectacular --color --file schema.yml        
        # installs yq
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
        chmod +x /usr/bin/yq
        # convert yaml to json
        echo 'CONVERTING TO JSON'
        yq -o=json '.' schema.yml > schema.json
        echo 'LISTING ALL FILES'
        ls
        
    
    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: 'schema.json'

